
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) NOT NULL,
                                     CONSTRAINT pk_user PRIMARY KEY (id),
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);
CREATE TABLE IF NOT EXISTS item_requests (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     description VARCHAR(512) NOT NULL,
                                     requester_id BIGINT REFERENCES users(id),
                                     created TIMESTAMP NOT NULL,
                                     CONSTRAINT pk_item_requests PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS items (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     description VARCHAR(512) NOT NULL,
                                     owner_id BIGINT REFERENCES users(id),
                                     status SMALLINT NOT NULL,
                                     request_id BIGINT REFERENCES item_requests(id),
                                     CONSTRAINT pk_items PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                     item_id BIGINT REFERENCES items(id),
                                     booker_id BIGINT REFERENCES users(id),
                                     status SMALLINT NOT NULL,
                                     start TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                     "end" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                     CHECK (bookings.start > CURRENT_TIMESTAMP),
                                     CHECK (bookings."end" > CURRENT_TIMESTAMP),
                                     CHECK (bookings.start < bookings."end"),
                                     CONSTRAINT pk_bookings PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                    text VARCHAR(1024),
                                    item_id BIGINT REFERENCES items(id),
                                    author_id BIGINT REFERENCES users(id),
                                    created TIMESTAMP NOT NULL,
                                    CONSTRAINT pk_comments PRIMARY KEY (id)
)